config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    confirmations: "users/confirmations",
    omniauths: "users/omniauths",
    passwords: "users/passwords",
    registrations: "users/registrations",
    sessions: "users/sessions",
    unlocks: "users/unlocks"
  }
  devise_scope :user do
    get "users/show", to: "users/registrations#show", as: "user_profile"
  end
  resources :questionnaires do
    post "csv/create", to: "questionnaires#create_from_csv"
    resource :questions, only: [:show, :edit, :update] do
      delete ":id", to: "questions#destroy"
    end

    resources :submissions
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "homes#landing_page"

  match "/:status", to: "errors#show", constraints: {status: /\d{3}/}, via: :all
end

app/models/question.rb
class Question < ApplicationRecord
  include Discard::Model

  belongs_to :questionnaire
  has_many :submission_values

  def mark_for_destruction
    if submission_values.any?
      discard!
      @marked_for_destruction = false
    else
      @marked_for_destruction = true
    end
  end

  validates :name,
    presence: true,
    length: {in: 1..50},
    format: {
      with: /\A[\w\ \&\(\)\-]+\z/,
      message: "can only contain alphabet, number, parentheses,and &-_"
    }

  validates :description, length: {in: 0..280}

  validates :value_type, presence: true
  enum value_type: {text: "text", number: "number", date: "date"}, _default: "text"

  # unfortunately, we can't use ruby's regex (even with to_s)
  def valid_pattern
    if number?
      '[\d.]*'
    else
      '[a-zA-Z0-9_\. \'\-\(\)]*'
    end
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  # def show
  # end

  def edit
    @questionnaire = current_user.questionnaires.find(params[:questionnaire_id])
  end

  def update
    @questionnaire = current_user.questionnaires.find(params[:questionnaire_id])
    if @questionnaire.update(questions_params)
      redirect_to questionnaire_path(@questionnaire)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # def destroy
  # end

  private

  def questions_params
    permitted_params = params.require(:questionnaire)
      .permit(
        questions_attributes: [:id, :name, :description, :value_type, :is_emptyable, :position, :_destroy]
      )

    # TODO: add position input
    permitted_params[:questions_attributes]&.each do |_, question_params|
      if question_params[:position].blank?
        question_params.merge!({position: 0})
      end
    end

    permitted_params
  end
end

app/views/questions/edit.html.erb
<div id="questionnaire-hero" class="card card--no-line">
  <h1><%= @questionnaire.title %></h1>
  <p><%= @questionnaire.description %></p>
</div>

<%= render 'questionnaires/subnavbar' %>

<div id="questionnaire-main-view" class="card">
  <%= form_with(model: @questionnaire, url: questionnaire_questions_path(@questionnaire), method: :put) do |f| %>
    <div id="question-form-actionbar" class="card" style="position: sticky; top: 20px; background-color: var(--surface-1); flex-flow: row;">
      <%= f.button class: "button", type: :button, data: { behaviour: 'add-question-form' }, style: "flex-grow: 3;" do %>
        <svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 -960 960 960" width="24px" fill="currentColor"><path d="M200-200v-160 4-4 160Zm0 80q-33 0-56.5-23.5T120-200v-160q0-33 23.5-56.5T200-440h560q33 0 56.5 23.5T840-360H200v160h400v80H200Zm0-400q-33 0-56.5-23.5T120-600v-160q0-33 23.5-56.5T200-840h560q33 0 56.5 23.5T840-760v160q0 33-23.5 56.5T760-520H200Zm0-80h560v-160H200v160Zm0 0v-160 160ZM760-40v-80h-80v-80h80v-80h80v80h80v80h-80v80h-80Z"/></svg>
        add question
      <% end %>
      <%= f.button class: "button", type: :button, data: { behaviour: 'show-questions-preview' } do %>
        <svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 -960 960 960" width="24px" fill="currentColor"><path d="M200-120q-33 0-56.5-23.5T120-200v-560q0-33 23.5-56.5T200-840h560q33 0 56.5 23.5T840-760v560q0 33-23.5 56.5T760-120H200Zm0-80h560v-480H200v480Zm280-80q-82 0-146.5-44.5T240-440q29-71 93.5-115.5T480-600q82 0 146.5 44.5T720-440q-29 71-93.5 115.5T480-280Zm0-60q56 0 102-26.5t72-73.5q-26-47-72-73.5T480-540q-56 0-102 26.5T306-440q26 47 72 73.5T480-340Zm0-100Zm0 60q25 0 42.5-17.5T540-440q0-25-17.5-42.5T480-500q-25 0-42.5 17.5T420-440q0 25 17.5 42.5T480-380Z"/></svg>
        preview
      <% end %>
    </div>

    <div id="questions-preview-modal" class="modal">
      <div class="modal__content">
        <div class="card" data-target="questions-preview-wrapper">
        </div>
        <p>click anywhere to close the preview</p>
      </div>
    </div>

    <% if @questionnaire.questions.blank? %>
      <div id="questionnaire-ghost-hint" class="card card--ghost" data-target="empty-state-ghost-section">
        <svg xmlns="http://www.w3.org/2000/svg" height="40px" viewBox="0 -960 960 960" width="40px" fill="currentColor"><path d="M186.67-813.33V-536.67v-2.66V-146.67v-666.66 190.66-190.66Zm92.66 400h161q11.67-19 26.17-35.67 14.5-16.67 31.83-31h-219v66.67Zm0 166.66h123q-2.33-16.66-2-33.33.34-16.67 2.67-33.33H279.33v66.66ZM186.67-80q-27 0-46.84-19.83Q120-119.67 120-146.67v-666.66q0-27 19.83-46.84Q159.67-880 186.67-880H534l226 226v134q-15.67-6.67-32.33-10.67-16.67-4-34.34-6v-86H500.67v-190.66h-314v666.66h249q11 19 24.5 35.67t29.5 31h-303Zm476.66-392.67q81.34 0 138.67 57.33 57.33 57.33 57.33 138.67 0 81.34-57.33 138.67-57.33 57.33-138.67 57.33-81.34 0-138.67-57.33-57.33-57.33-57.33-138.67 0-81.34 57.33-138.67 57.33-57.33 138.67-57.33Zm.74 318.67q11.6 0 19.43-7.91 7.83-7.9 7.83-19.5 0-11.59-7.9-19.42-7.91-7.84-19.5-7.84-11.6 0-19.43 7.91-7.83 7.9-7.83 19.5 0 11.59 7.9 19.43 7.91 7.83 19.5 7.83Zm-19.4-80h38.66v-10.63q0-11.7 6.34-21.2 6.33-9.5 14.81-17.77 14.85-12.4 23.85-24.4 9-12 9-32 0-30.81-20.53-49.41Q696.27-408 663.85-408q-24.85 0-45.02 14.17-20.16 14.16-28.16 38.82L625.33-340q2.34-13.33 13.17-22.67 10.83-9.33 25.8-9.33 16.03 0 25.2 8 9.17 8 9.17 24 0 11-6.67 19.17-6.67 8.16-14.67 16.16-7.33 6.67-14.5 13.34-7.16 6.66-12.16 14.66-3.67 6.67-4.84 12.87-1.16 6.2-1.16 14.47V-234Z"/></svg>
        <p>no question found, let's add one by clicking button above</p>
      </div>
    <% end %>

    <section id="question-form-cards-wrapper" data-target="questions-wrapper">
      <%= f.fields_for :questions, @questionnaire.questions.kept do |existing_question_f| %>
        <div class="card question-form">
          <%= existing_question_f.hidden_field :id %>
          <%= existing_question_f.hidden_field :position %>
          <%= existing_question_f.hidden_field :_destroy, value: "0" %>

          <fieldset class="field field--inline">
            <%= existing_question_f.label :name %>
            <%= existing_question_f.text_field :name %>
          </fieldset>

          <fieldset class="field field--inline">
            <%= existing_question_f.label :description %>
            <%= existing_question_f.text_field :description %>
          </fieldset>

          <fieldset class="field">
            <%= existing_question_f.label :value_type %>
            <%= existing_question_f.select :value_type, Question.value_types %>
            <span style="color: var(--surface-3);">|</span>
            <%= existing_question_f.check_box :is_emptyable %>
            <%= existing_question_f.label :is_emptyable, class: "checkable" %>
          </fieldset>

          <fieldset class="field actions">
            <%= f.button class: "button", type: :button, data: { behaviour: 'change-question-position-up' } do %>
              <svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 -960 960 960" width="24px" fill="currentColor"><path d="M440-160v-487L216-423l-56-57 320-320 320 320-56 57-224-224v487h-80Z"/></svg>
              move up
            <% end %>
            <%= f.button class: "button", type: :button, data: { behaviour: 'remove-question-form' } do %>
              <svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 -960 960 960" width="24px" fill="currentColor"><path d="m500-120-56-56 142-142-142-142 56-56 142 142 142-142 56 56-142 142 142 142-56 56-142-142-142 142Zm-220 0v-80h80v80h-80Zm-80-640h-80q0-33 23.5-56.5T200-840v80Zm80 0v-80h80v80h-80Zm160 0v-80h80v80h-80Zm160 0v-80h80v80h-80Zm160 0v-80q33 0 56.5 23.5T840-760h-80ZM200-200v80q-33 0-56.5-23.5T120-200h80Zm-80-80v-80h80v80h-80Zm0-160v-80h80v80h-80Zm0-160v-80h80v80h-80Zm640 0v-80h80v80h-80Z"/></svg>
              remove
            <% end %>
            <%= f.button class: "button", type: :button, data: { behaviour: 'change-question-position-down' } do %>
              <svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 -960 960 960" width="24px" fill="currentColor"><path d="M440-800v487L216-537l-56 57 320 320 320-320-56-57-224 224v-487h-80Z"/></svg>
              move down
            <% end %>
          </fieldset>
        </div>
      <% end %>
    </section>

    <template data-target="question-form-template">
      <div class="card question-form">
        <%# CHILDIDTEMPLATE will modified by jquery %>
        <%= f.fields_for :questions, @questionnaire.questions.new, child_index: 'CHILDIDTEMPLATE' do |question_f| %>
          <%= question_f.hidden_field :position %>
          <%= question_f.hidden_field :_destroy, value: "0" %>

          <fieldset class="field field--inline">
            <%= question_f.label :name %>
            <%= question_f.text_field :name %>
          </fieldset>

          <fieldset class="field field--inline">
            <%= question_f.label :description %>
            <%= question_f.text_field :description %>
          </fieldset>

          <fieldset class="field">
            <%= question_f.label :value_type %>
            <%= question_f.select :value_type, Question.value_types %>
            <span style="color: var(--surface-3);">|</span>
            <%= question_f.check_box :is_emptyable %>
            <%= question_f.label :is_emptyable, class: "checkable" %>
          </fieldset>

          <fieldset class="field actions">
            <%= f.button class: "button", type: :button, data: { behaviour: 'change-question-position-up' } do %>
              <svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 -960 960 960" width="24px" fill="currentColor"><path d="M440-160v-487L216-423l-56-57 320-320 320 320-56 57-224-224v487h-80Z"/></svg>
              move up
            <% end %>
            <%= f.button class: "button", type: :button, data: { behaviour: 'remove-question-form' } do %>
              <svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 -960 960 960" width="24px" fill="currentColor"><path d="m500-120-56-56 142-142-142-142 56-56 142 142 142-142 56 56-142 142 142 142-56 56-142-142-142 142Zm-220 0v-80h80v80h-80Zm-80-640h-80q0-33 23.5-56.5T200-840v80Zm80 0v-80h80v80h-80Zm160 0v-80h80v80h-80Zm160 0v-80h80v80h-80Zm160 0v-80q33 0 56.5 23.5T840-760h-80ZM200-200v80q-33 0-56.5-23.5T120-200h80Zm-80-80v-80h80v80h-80Zm0-160v-80h80v80h-80Zm0-160v-80h80v80h-80Zm640 0v-80h80v80h-80Z"/></svg>
              remove
            <% end %>
            <%= f.button class: "button", type: :button, data: { behaviour: 'change-question-position-down' } do %>
              <svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 -960 960 960" width="24px" fill="currentColor"><path d="M440-800v487L216-537l-56 57 320 320 320-320-56-57-224 224v-487h-80Z"/></svg>
              move down
            <% end %>
          </fieldset>
        <% end %>
      </div>
    </template>

    <template data-target="question-preview-template">
      <fieldset class="field field--stacked" disabled>
        <p style="display: flex; align-items: center; gap: 2px;"></p>
        <input type="text">
      </fieldset>
    </template>

    <div class="actions">
      <%= f.submit "save questions", class: "button" %>
    </div>
  <% end %>
</div>

app/views/questions/show.html.erb
<h1><%= @questionnaire.title %></h1>
<p><%= @questionnaire.description %></p>