config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    confirmations: "users/confirmations",
    omniauths: "users/omniauths",
    passwords: "users/passwords",
    registrations: "users/registrations",
    sessions: "users/sessions",
    unlocks: "users/unlocks"
  }
  devise_scope :user do
    get "users/show", to: "users/registrations#show", as: "user_profile"
  end
  resources :questionnaires do
    post "csv/create", to: "questionnaires#create_from_csv"
    resource :questions, only: [:show, :edit, :update] do
      delete ":id", to: "questions#destroy"
    end

    resources :submissions
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "homes#landing_page"

  match "/:status", to: "errors#show", constraints: {status: /\d{3}/}, via: :all
end

app/models/submission.rb
class Submission < ApplicationRecord
  belongs_to :questionnaire
  has_many :submission_values, dependent: :destroy
  accepts_nested_attributes_for :submission_values, allow_destroy: true

  def whole_submission_values
    existing_submission_values = submission_values.index_by { |sv| [sv.submission_id, sv.question_id] }

    result = []
    questionnaire.questions.kept.each do |q|
      key = [id, q.id]

      result << (existing_submission_values[key] || SubmissionValue.new(
        questionnaire: questionnaire,
        submission: self,
        question: q
      ))
    end

    result
  end
end

app/controllers/submissions_controller.rb
class SubmissionsController < ApplicationController
  def new
    @questionnaire = current_user.questionnaires.find(params[:questionnaire_id])

    @questions = @questionnaire.questions.kept

    if @questions.blank?
      redirect_to(questionnaire_path(@questionnaire), alert: "current questionnaire doesn't have any questions yet") and return
    end

    @old_submission = nil
    if prefill_with_prev_submission_params
      @old_submission = @questionnaire.submissions.last
    end

    @submission = @questionnaire.submissions.new
    @questionnaire.questions.kept.each do |question|
      @submission.submission_values.new(question: question)
    end
  end

  def create
    @questionnaire = current_user.questionnaires.find(params[:questionnaire_id])
    @submission = @questionnaire.submissions.new(submission_params)

    if @submission.save
      redirect_to questionnaire_path(@questionnaire)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @questionnaire = current_user.questionnaires.find(params[:questionnaire_id])
    @submission = @questionnaire.submissions.find(params[:id])
  end

  def update
    @questionnaire = current_user.questionnaires.find(params[:questionnaire_id])
    @submission = @questionnaire.submissions.find(params[:id])

    if @submission.update(submission_params)
      redirect_to questionnaire_path(@questionnaire)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @questionnaire = current_user.questionnaires.find(params[:questionnaire_id])
    @submission = @questionnaire.submissions.find(params[:id])

    @submission.destroy!
    redirect_to questionnaire_path(@questionnaire)
  end

  private

  def prefill_with_prev_submission_params
    ActiveRecord::Type::Boolean.new.cast(params[:prefill_with_prev_submission])
  end

  def submission_params
    params.require(:submission)
      .permit(submission_values_attributes: [:id, :question_id, :value])
  end
end

app/views/submissions/edit.html.erb
<div id="#questionnaire-hero" class="card card--no-line">
  <h1><%= @questionnaire.title %></h1>
  <p><%= @questionnaire.description %></p>
</div>

<%= render 'questionnaires/subnavbar' %>

<div id="questionnaire-main-view" class="card">
  <%= form_with(model: @submission, url: questionnaire_submission_path(@questionnaire, @submission), method: :put) do |f| %>
      <%= f.fields_for :submission_values, @submission.whole_submission_values do |submission_values_f| %>
        <fieldset class="field field--stacked">
          <% submission_value = submission_values_f.object %>
          <% question = submission_value.question %>
          <%= submission_values_f.hidden_field :id, value: submission_value.id %>
          <%= submission_values_f.hidden_field :question_id, value: question.id %>
          <%= submission_values_f.label :value do %>
            <%= question.name %> <span class="mini-label"><%= question.value_type %></span>
            <% unless question.is_emptyable? %>
              <span class="mini-label">required</span>
            <% end %>
            <% if submission_value.errors.any? %>
              <em>(<%= submission_value.errors[:value].join("; ") %>)</em>
            <% end %>
          <% end %>
          <% if question.date? %>
            <%= submission_values_f.date_field :value, required: !question.is_emptyable?, value: submission_value.value %>
          <% else %>
            <%= submission_values_f.text_field :value, required: !question.is_emptyable?, pattern: question.valid_pattern %>
          <% end %>
        </fieldset>
    <% end %>

    <div class="actions">
      <%= f.submit "update submission", class: "button" %>
      <%= link_to "back", questionnaire_path(@questionnaire), class: "button" %>
    </div>
  <% end %>
</div>

app/views/submissions/new.html.erb
<div id="#questionnaire-hero" class="card card--no-line">
  <h1><%= @questionnaire.title %></h1>
  <p><%= @questionnaire.description %></p>
</div>

<%= render 'questionnaires/subnavbar' %>

<div id="questionnaire-main-view" class="card">
  <%= form_with(model: @submission, url: questionnaire_submissions_path(@questionnaire), method: :post) do |f| %>
      <%= f.fields_for :submission_values do |submission_values_f| %>
        <fieldset class="field field--stacked">
          <% submission_value = submission_values_f.object %>
          <% question = submission_value.question %>
          <%= submission_values_f.hidden_field :question_id, value: question.id %>
          <%= submission_values_f.label :value do %>
            <%= question.name %>
            <span class="mini-label"><%= question.value_type %></span>
            <% unless question.is_emptyable? %>
              <span class="mini-label">required</span>
            <% end %>
            <% if submission_value.errors.any? %>
              <em>(<%= submission_value.errors[:value].join("; ") %>)</em>
            <% end %>
          <% end %>
          <% if question.date? %>
            <%= submission_values_f.date_field :value, required: !question.is_emptyable?, value: @old_submission&.submission_values&.find_by(question: question)&.value %>
          <% else %>
            <%= submission_values_f.text_field :value, required: !question.is_emptyable?, pattern: question.valid_pattern, value: @old_submission&.submission_values&.find_by(question: question)&.value %>
          <% end %>
        </fieldset>
    <% end %>

    <div class="actions">
      <%= f.submit "save submission", class: "button" %>
      <%= link_to new_questionnaire_submission_path(@questionnaire, prefill_with_prev_submission: true), class: "button" do %>
        <svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 -960 960 960" width="24px" fill="currentColor"><path d="M360-280q-33 0-56.5-23.5T280-360v-400q0-33 23.5-56.5T360-840h400q33 0 56.5 23.5T840-760v400q0 33-23.5 56.5T760-280H360Zm0-80h400v-400H360v400ZM200-200v80q-33 0-56.5-23.5T120-200h80Zm-80-80v-80h80v80h-80Zm0-160v-80h80v80h-80Zm0-160v-80h80v80h-80Zm160 480v-80h80v80h-80Zm160 0v-80h80v80h-80Zm160 0v-80h80v80h-80Z"/></svg>
        prefill with previous submission
      <% end %>
    </div>
  <% end %>
</div>