config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    confirmations: "users/confirmations",
    omniauths: "users/omniauths",
    passwords: "users/passwords",
    registrations: "users/registrations",
    sessions: "users/sessions",
    unlocks: "users/unlocks"
  }
  devise_scope :user do
    get "users/show", to: "users/registrations#show", as: "user_profile"
  end
  resources :questionnaires do
    post "csv/create", to: "questionnaires#create_from_csv"
    resource :questions, only: [:show, :edit, :update] do
      delete ":id", to: "questions#destroy"
    end

    resources :submissions
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "homes#landing_page"

  match "/:status", to: "errors#show", constraints: {status: /\d{3}/}, via: :all
end

app/models/questionnaire.rb
class Questionnaire < ApplicationRecord
  belongs_to :user

  validates :title,
    presence: true,
    length: {in: 1..100},
    format: {
      with: /\A[\w\ \&\(\)\-]+\z/,
      message: "can only contain alphabet, number, parentheses,and &-_"
    }

  validates :description, length: {in: 0..280}

  has_many :questions, -> { order(position: :asc, name: :asc) }, dependent: :destroy
  accepts_nested_attributes_for :questions, allow_destroy: true

  has_many :submissions, dependent: :destroy
  has_many :submission_values, dependent: :destroy
end

app/controllers/questionnaires_controller.rb
class QuestionnairesController < ApplicationController
  before_action :authenticate_user!

  def index
    @questionnaires = current_user.questionnaires
  end

  def new
    @questionnaire = Questionnaire.new
  end

  def create
    @questionnaire = current_user.questionnaires.new(questionnaire_params)

    if @questionnaire.save
      redirect_to questionnaire_path(@questionnaire)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @questionnaire = current_user.questionnaires.find(params[:id])
  end

  def create_from_csv
    @questionnaire = Questionnaire.find(params[:questionnaire_id])

    begin
      CsvParserJob.new.perform(@questionnaire.id, params[:csv_file].tempfile.read)
    rescue CSV::MalformedCSVError => e
      redirect_to(questionnaire_path(@questionnaire), alert: "Can't parse document: #{e.message}") and return
    rescue ActiveRecord::ActiveRecordError => e
      redirect_to(questionnaire_path(@questionnaire), alert: "#{e.message}") and return
    end

    redirect_to(questionnaire_path(@questionnaire)) and return
  end

  private

  def questionnaire_params
    params.require(:questionnaire)
      .permit(
        :title,
        :description
      )
  end
end

app/views/questionnaires/_subnavbar.html.erb
<div id="questionnaire-subnavbar" class="actions">
  <% if @questionnaire.questions.blank? %>
    <button class="button button--disabled" disabled>
      <svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 -960 960 960" width="24px" fill="currentColor"><path d="M200-560h560v-240H200v240Zm-80 400v-720h720v720H680v-80h80v-240H200v240h80v80H120Zm360-320Zm0-80v80-80Zm0 0ZM440-80v-80h-80v-80h80v-80h80v80h80v80h-80v80h-80Z"/></svg>
      log new data
    </button>
  <% elsif !current_page?(new_questionnaire_submission_path(@questionnaire)) %>
    <%= link_to new_questionnaire_submission_path(@questionnaire), class: "button" do %>
      <svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 -960 960 960" width="24px" fill="currentColor"><path d="M200-560h560v-240H200v240Zm-80 400v-720h720v720H680v-80h80v-240H200v240h80v80H120Zm360-320Zm0-80v80-80Zm0 0ZM440-80v-80h-80v-80h80v-80h80v80h80v80h-80v80h-80Z"/></svg>
      log new data
    <% end %>
  <% else %>
    <button class="button button--active" disabled>
      <svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 -960 960 960" width="24px" fill="currentColor"><path d="M200-560h560v-240H200v240Zm-80 400v-720h720v720H680v-80h80v-240H200v240h80v80H120Zm360-320Zm0-80v80-80Zm0 0ZM440-80v-80h-80v-80h80v-80h80v80h80v80h-80v80h-80Z"/></svg>
      log new data
    </button>
  <% end %>

  <% if !current_page?(questionnaire_path(@questionnaire)) %>
    <%= link_to questionnaire_path(@questionnaire), class: "button" do %>
      <svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 -960 960 960" width="24px" fill="currentColor"><path d="M200-120q-33 0-56.5-23.5T120-200v-560q0-33 23.5-56.5T200-840h560q33 0 56.5 23.5T840-760v560q0 33-23.5 56.5T760-120H200Zm240-240H200v160h240v-160Zm80 0v160h240v-160H520Zm-80-80v-160H200v160h240Zm80 0h240v-160H520v160ZM200-680h560v-80H200v80Z"/></svg>
      data
    <% end %>
  <% else %>
    <button class="button button--active" disabled>
      <svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 -960 960 960" width="24px" fill="currentColor"><path d="M200-120q-33 0-56.5-23.5T120-200v-560q0-33 23.5-56.5T200-840h560q33 0 56.5 23.5T840-760v560q0 33-23.5 56.5T760-120H200Zm240-240H200v160h240v-160Zm80 0v160h240v-160H520Zm-80-80v-160H200v160h240Zm80 0h240v-160H520v160ZM200-680h560v-80H200v80Z"/></svg>
      data
    </button>
  <% end %>

  <% if !current_page?(edit_questionnaire_questions_path(@questionnaire)) %>
    <%= link_to edit_questionnaire_questions_path(@questionnaire), class: "button" do %>
      <svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 -960 960 960" width="24px" fill="currentColor"><path d="M200-440h240v-160H200v160Zm0-240h560v-80H200v80Zm0 560q-33 0-56.5-23.5T120-200v-560q0-33 23.5-56.5T200-840h560q33 0 56.5 23.5T840-760v252q-19-8-39.5-10.5t-40.5.5q-21 4-40.5 13.5T684-479l-39 39-205 204v116H200Zm0-80h240v-160H200v160Zm320-240h125l39-39q16-16 35.5-25.5T760-518v-82H520v160Zm0 360v-123l221-220q9-9 20-13t22-4q12 0 23 4.5t20 13.5l37 37q8 9 12.5 20t4.5 22q0 11-4 22.5T863-300L643-80H520Zm300-263-37-37 37 37ZM580-140h38l121-122-37-37-122 121v38Zm141-141-19-18 37 37-18-19Z"/></svg>
      edit structure
    <% end %>
  <% else %>
    <button class="button button--active" disabled>
      <svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 -960 960 960" width="24px" fill="currentColor"><path d="M200-440h240v-160H200v160Zm0-240h560v-80H200v80Zm0 560q-33 0-56.5-23.5T120-200v-560q0-33 23.5-56.5T200-840h560q33 0 56.5 23.5T840-760v252q-19-8-39.5-10.5t-40.5.5q-21 4-40.5 13.5T684-479l-39 39-205 204v116H200Zm0-80h240v-160H200v160Zm320-240h125l39-39q16-16 35.5-25.5T760-518v-82H520v160Zm0 360v-123l221-220q9-9 20-13t22-4q12 0 23 4.5t20 13.5l37 37q8 9 12.5 20t4.5 22q0 11-4 22.5T863-300L643-80H520Zm300-263-37-37 37 37ZM580-140h38l121-122-37-37-122 121v38Zm141-141-19-18 37 37-18-19Z"/></svg>
      edit structure
    </button>
  <% end %>
</div>

app/views/questionnaires/index.html.erb
<h1>Questionnaires</h1>

<div class="actions">
  <%= link_to new_questionnaire_path do %>
    <button class="button">
      <svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 -960 960 960" width="24px" fill="currentColor"><path d="M200-120q-33 0-56.5-23.5T120-200v-560q0-33 23.5-56.5T200-840h560q33 0 56.5 23.5T840-760v268q-19-9-39-15.5t-41-9.5v-243H200v560h242q3 22 9.5 42t15.5 38H200Zm0-120v40-560 243-3 280Zm80-40h163q3-21 9.5-41t14.5-39H280v80Zm0-160h244q32-30 71.5-50t84.5-27v-3H280v80Zm0-160h400v-80H280v80ZM720-40q-83 0-141.5-58.5T520-240q0-83 58.5-141.5T720-440q83 0 141.5 58.5T920-240q0 83-58.5 141.5T720-40Zm-20-80h40v-100h100v-40H740v-100h-40v100H600v40h100v100Z"/></svg>
      new questionnaire
    </button>
  <% end %>
</div>

<% if @questionnaires.present? %>
  <div class="cards-container">
    <% @questionnaires.each do |questionnaire| %>
      <%= link_to questionnaire_path(questionnaire) do %>
        <div class="card">
          <header><%= questionnaire.title %></header>
        </div>
      <% end %>
    <% end %>
  </div>
<% else %>
  <%= link_to new_questionnaire_path do %>
    <div class="card card--ghost">
      <svg xmlns="http://www.w3.org/2000/svg" height="40px" viewBox="0 -960 960 960" width="40px" fill="currentColor"><path d="M186.67-813.33V-536.67v-2.66V-146.67v-666.66 190.66-190.66Zm92.66 400h161q11.67-19 26.17-35.67 14.5-16.67 31.83-31h-219v66.67Zm0 166.66h123q-2.33-16.66-2-33.33.34-16.67 2.67-33.33H279.33v66.66ZM186.67-80q-27 0-46.84-19.83Q120-119.67 120-146.67v-666.66q0-27 19.83-46.84Q159.67-880 186.67-880H534l226 226v134q-15.67-6.67-32.33-10.67-16.67-4-34.34-6v-86H500.67v-190.66h-314v666.66h249q11 19 24.5 35.67t29.5 31h-303Zm476.66-392.67q81.34 0 138.67 57.33 57.33 57.33 57.33 138.67 0 81.34-57.33 138.67-57.33 57.33-138.67 57.33-81.34 0-138.67-57.33-57.33-57.33-57.33-138.67 0-81.34 57.33-138.67 57.33-57.33 138.67-57.33Zm.74 318.67q11.6 0 19.43-7.91 7.83-7.9 7.83-19.5 0-11.59-7.9-19.42-7.91-7.84-19.5-7.84-11.6 0-19.43 7.91-7.83 7.9-7.83 19.5 0 11.59 7.9 19.43 7.91 7.83 19.5 7.83Zm-19.4-80h38.66v-10.63q0-11.7 6.34-21.2 6.33-9.5 14.81-17.77 14.85-12.4 23.85-24.4 9-12 9-32 0-30.81-20.53-49.41Q696.27-408 663.85-408q-24.85 0-45.02 14.17-20.16 14.16-28.16 38.82L625.33-340q2.34-13.33 13.17-22.67 10.83-9.33 25.8-9.33 16.03 0 25.2 8 9.17 8 9.17 24 0 11-6.67 19.17-6.67 8.16-14.67 16.16-7.33 6.67-14.5 13.34-7.16 6.66-12.16 14.66-3.67 6.67-4.84 12.87-1.16 6.2-1.16 14.47V-234Z"/></svg>
      <p>
        Empty questionnaire, create one?
      </p>
    </div>
  <% end %>
<% end %>

app/views/questionnaires/new.html.erb
<h1>Create Questionnaires</h1>

<div class="card">
  <%= form_with(model: @questionnaire) do |f| %>
    <% if @questionnaire.errors.any? %>
      <div class="card">
        <div id="error_explanation" data-turbo-cache="false">
          <ul>
            <% @questionnaire.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      </div>
    <% end %>

    <fieldset class="field field--stacked">
      <%= f.label :title %>
      <%= f.text_field :title, autofocus: true %>
    </fieldset>

    <fieldset class="field field--stacked">
      <%= f.label :description %>
      <%=
        f.text_area :description, autofocus: true,
          style: "resize: vertical; min-height: 100px"
      %>
    </fieldset>

    <div class="actions">
      <%= f.submit "create questionnaire", class: "button" %>
    </div>
  <% end %>
</div>

app/views/questionnaires/show.html.erb
<div id="questionnaire-hero" class="card card--no-line">
  <h1><%= @questionnaire.title %></h1>
  <p><%= @questionnaire.description %></p>
</div>

<%= render 'questionnaires/subnavbar' %>

<div id="questionnaire-main-view" class="card" style="max-height: 80vh; overflow: scroll;">
  <% if @questionnaire.questions.present? %>
    <table id="questionnaire-table">
      <thead>
      <tr>
        <% @questionnaire.questions.kept.each do |question| %>
          <th><%= question.name %></th>
        <% end %>
        <th>created at</th>
        <th>updated at</th>
      </tr>
      </thead>
      <tbody>
      <% @questionnaire.submissions.each do |submission| %>
        <tr>
          <% submission.whole_submission_values.each do |submission_value| %>
            <td><%= submission_value.value %></td>
          <% end %>
          <td><%= submission.created_at.to_formatted_s(:short) %></td>
          <td><%= submission.updated_at.to_formatted_s(:short) %></td>
          <td style="display: flex; gap: 2px;">
            <%= link_to "edit", edit_questionnaire_submission_path(@questionnaire, submission), class: "button" %>
            <%= link_to "remove", questionnaire_submission_path(@questionnaire, submission), class: "button", data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  <% else %>
    <div id="questionnaire-ghost-hint" class="card card--ghost-stacked">
      <svg xmlns="http://www.w3.org/2000/svg" height="40px" viewBox="0 -960 960 960" width="40px" fill="currentColor"><path d="M186.67-813.33V-536.67v-2.66V-146.67v-666.66 190.66-190.66Zm92.66 400h161q11.67-19 26.17-35.67 14.5-16.67 31.83-31h-219v66.67Zm0 166.66h123q-2.33-16.66-2-33.33.34-16.67 2.67-33.33H279.33v66.66ZM186.67-80q-27 0-46.84-19.83Q120-119.67 120-146.67v-666.66q0-27 19.83-46.84Q159.67-880 186.67-880H534l226 226v134q-15.67-6.67-32.33-10.67-16.67-4-34.34-6v-86H500.67v-190.66h-314v666.66h249q11 19 24.5 35.67t29.5 31h-303Zm476.66-392.67q81.34 0 138.67 57.33 57.33 57.33 57.33 138.67 0 81.34-57.33 138.67-57.33 57.33-138.67 57.33-81.34 0-138.67-57.33-57.33-57.33-57.33-138.67 0-81.34 57.33-138.67 57.33-57.33 138.67-57.33Zm.74 318.67q11.6 0 19.43-7.91 7.83-7.9 7.83-19.5 0-11.59-7.9-19.42-7.91-7.84-19.5-7.84-11.6 0-19.43 7.91-7.83 7.9-7.83 19.5 0 11.59 7.9 19.43 7.91 7.83 19.5 7.83Zm-19.4-80h38.66v-10.63q0-11.7 6.34-21.2 6.33-9.5 14.81-17.77 14.85-12.4 23.85-24.4 9-12 9-32 0-30.81-20.53-49.41Q696.27-408 663.85-408q-24.85 0-45.02 14.17-20.16 14.16-28.16 38.82L625.33-340q2.34-13.33 13.17-22.67 10.83-9.33 25.8-9.33 16.03 0 25.2 8 9.17 8 9.17 24 0 11-6.67 19.17-6.67 8.16-14.67 16.16-7.33 6.67-14.5 13.34-7.16 6.66-12.16 14.66-3.67 6.67-4.84 12.87-1.16 6.2-1.16 14.47V-234Z"/></svg>
      <p>no question found, you can</p>
      <div class="actions">
        <%= link_to edit_questionnaire_questions_path(@questionnaire), class: "button" do %>
          <svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 -960 960 960" width="24px" fill="currentColor"><path d="M200-440h240v-160H200v160Zm0-240h560v-80H200v80Zm0 560q-33 0-56.5-23.5T120-200v-560q0-33 23.5-56.5T200-840h560q33 0 56.5 23.5T840-760v252q-19-8-39.5-10.5t-40.5.5q-21 4-40.5 13.5T684-479l-39 39-205 204v116H200Zm0-80h240v-160H200v160Zm320-240h125l39-39q16-16 35.5-25.5T760-518v-82H520v160Zm0 360v-123l221-220q9-9 20-13t22-4q12 0 23 4.5t20 13.5l37 37q8 9 12.5 20t4.5 22q0 11-4 22.5T863-300L643-80H520Zm300-263-37-37 37 37ZM580-140h38l121-122-37-37-122 121v38Zm141-141-19-18 37 37-18-19Z"/></svg>
          initiate structure
        <% end %>
        <p>or</p>
        <%= button_tag type: :button, class: "button", data: {behaviour: 'show-csv-upload-modal'} do %>
          <svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 -960 960 960" width="24px" fill="currentColor"><path d="M440-320v-326L336-542l-56-58 200-200 200 200-56 58-104-104v326h-80ZM240-160q-33 0-56.5-23.5T160-240v-120h80v120h480v-120h80v120q0 33-23.5 56.5T720-160H240Z"/></svg>
          upload csv
        <% end %>
      </div>
    </div>
  <% end %>
</div>

<div class="modal">
  <div class="modal__content">
    <div class="card" data-target="questionnaire-csv-upload-form-wrapper">
      <button class="modal__content__close_btn">
        <svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 -960 960 960" width="24px" fill="currentColor"><path d="m336-280-56-56 144-144-144-143 56-56 144 144 143-144 56 56-144 143 144 144-56 56-143-144-144 144Z"/></svg>
      </button>
      <%= form_with(url: questionnaire_csv_create_path(@questionnaire), method: :post) do |f| %>
        <%= f.label :csv_file, id: "questionnaire_csv_file", class: "field__dropfile" do %>
          <div class="card card--ghost-stacked">
            <%= f.file_field :csv_file, accept: ".csv" %> 
            <svg xmlns="http://www.w3.org/2000/svg" height="48px" viewBox="0 -960 960 960" width="48px" fill="currentColor"><path d="M452-202h60v-201l82 82 42-42-156-152-154 154 42 42 84-84v201ZM220-80q-24 0-42-18t-18-42v-680q0-24 18-42t42-18h361l219 219v521q0 24-18 42t-42 18H220Zm331-554v-186H220v680h520v-494H551ZM220-820v186-186 680-680Z"/></svg>
            <p class="field__dropfile__text">upload a csv file...</p>
          </div>

          <div class="actions">
            <%= f.submit "generate questions", class: "button button--full" %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>