config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    confirmations: "users/confirmations",
    omniauths: "users/omniauths",
    passwords: "users/passwords",
    registrations: "users/registrations",
    sessions: "users/sessions",
    unlocks: "users/unlocks"
  }
  devise_scope :user do
    get "users/show", to: "users/registrations#show", as: "user_profile"
  end
  resources :questionnaires do
    post "csv/create", to: "questionnaires#create_from_csv"
    resource :questions, only: [:show, :edit, :update] do
      delete ":id", to: "questions#destroy"
    end

    resources :submissions
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "homes#landing_page"

  match "/:status", to: "errors#show", constraints: {status: /\d{3}/}, via: :all
end

app/views/layouts/_navbar.html.erb
<nav class="nav">
  <div class="nav__brand">
    <svg width="10.902mm" height="9.4499mm" version="1.1" fill="currentColor" viewBox="0 0 10.902 9.4499" xmlns="http://www.w3.org/2000/svg">
     <g transform="translate(-66.075 -90.557)">
      <path transform="matrix(.26458 0 0 .26458 66.075 90.557)" d="m31.188 1.5117v4.7734h-4.8574v.98438h-3.6582v-1.0645h-21.16v28h21.68v-.75195h9.625a.49741.49741 0 00.49414-.49414v-12.594-5.8828h1.498v-4.7734h4.8848v-3.4238h-4.8848v-4.7734h-3.6211zm-8.5156 6.7559h3.6582v1.4414h4.8574v4.7734h1.127v5.3809h-11.363v-2.3789h-12.842v-6.0801h14.562v-3.1367zm-1.7207 12.594h11.363v11.604h-9.123v-3.4609h-15.082v-6.4805h12.842v-1.6621z"/>
     </g>
    </svg>
  </div>
  <div class="nav__menu">
  <% if user_signed_in? %>
    <%= link_to 'questionnaires', questionnaires_path, class: "button" %>
    <%= link_to 'profile', user_profile_path, class: "button" %>
    <%= link_to 'sign out', destroy_user_session_path, id: "user_sign_out", class: "button", data: { turbo_method: :delete } %>
  <% else %>
    <% if !current_page?(new_user_registration_path) %>
      <%= link_to new_user_registration_path, class: 'button' do %>
        <span>sign up</span>
      <% end %>
    <% end %>
    <% if !current_page?(new_user_session_path) %>
      <%= link_to new_user_session_path, class: 'button' do %>
        <svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 -960 960 960" width="24px" fill="currentColor"><path d="M480-120v-80h280v-560H480v-80h280q33 0 56.5 23.5T840-760v560q0 33-23.5 56.5T760-120H480Zm-80-160-55-58 102-102H120v-80h327L345-622l55-58 200 200-200 200Z"/></svg>
        <span>sign in</span>
      <% end %>
    <% end %>
  <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Entrii</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_include_tag 'application', 'data-turbo-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>
    <%= stylesheet_pack_tag 'application' %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  </head>

  <body class="application-layout" data-turbo-prefetch="false">
    <%= render 'layouts/navbar' %>
    <main class="application-mainview">
      <% if notice %>
        <div class="alert alert--info">
          <svg class="alert__icon" xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 -960 960 960" width="24px" fill="currentColor"><path d="M160-200v-80h80v-280q0-83 50-147.5T420-792v-28q0-25 17.5-42.5T480-880q25 0 42.5 17.5T540-820v28q80 20 130 84.5T720-560v280h80v80H160Zm320-300Zm0 420q-33 0-56.5-23.5T400-160h160q0 33-23.5 56.5T480-80ZM320-280h320v-280q0-66-47-113t-113-47q-66 0-113 47t-47 113v280Z"/></svg>
          <p class="alert__text"><%= notice %></p>
        </div>
      <% end %>

      <% if alert %>
        <div class="alert alert--warning">
          <svg class="alert__icon" xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 -960 960 960" width="24px" fill="currentColor"><path d="m40-120 440-760 440 760H40Zm138-80h604L480-720 178-200Zm302-40q17 0 28.5-11.5T520-280q0-17-11.5-28.5T480-320q-17 0-28.5 11.5T440-280q0 17 11.5 28.5T480-240Zm-40-120h80v-200h-80v200Zm40-100Z"/></svg>
          <p class="alert__text"><%= alert %></p>
        </div>
      <% end %>

      <div>
        <%= yield %>
      </div>
    </main>
  </body>
</html>